### ISSUE TITLE
Test: Highlighting Selectable Objects

### ISSUE THREAD

**Issue by robert-beall** [jdoiron94/Outside-The-Box#12]
Selectable Objects should be highlighted green.

**Comment by Femista** [comment]
Works, but need to get the x button to work every time.

**Comment by jdoiron94** [comment]
It has to do with how events fire. When you press x, it actually registers it being pressed many times. To get it to work 100%, someone will need to make instance variables to InputManager which track the last key pressed and last key released. Assuming both values equal x, then allow either object selection state to trigger. This will make it only work when the key is entirely pressed and released.

**Comment by jdoiron94** [comment]
Fixed. You can test this again to ensure it works, Femi.

**Comment by Femista** [comment]
Everything checks out on my end!
