### ISSUE TITLE
Test: Implement Mana System and Mana Bar

### ISSUE THREAD

**Issue by robert-beall** [jdoiron94/Outside-The-Box#15]
-Mana should start at a base value and increase with experience at a certain rate (100 xp to 1 point?) 

-Mana should regenerate at a certain rate and the mana bar should reflect this. 

-Mana Bar should use same base effect as health bar, but should be blue instead of red.

**Comment by jdoiron94** [comment]
Should be ready to test.

**Comment by Femista** [comment]
Works well, but should regenerate faster.

**Comment by jdoiron94** [comment]
Changed. It now regenerates on an exp-based system, capping at 10 hp/mp per cycle. It'll still act the same now, but when the user has exp, it'll serve them well. No reason to test this, so I'll mark it as done.
