### ISSUE TITLE
Create a base ability class that all powers will work through. 

### ISSUE THREAD

**Issue by Nazshiaakk** [jdoiron94/Outside-The-Box#18]
-Mana Cost. 
-Cooldown. 
-Texture
-Boundaries (if it has a texture)
-Abstract/virtual method that can be overridden. 
-activation key (character)

**Comment by jdoiron94** [comment]
This is pretty much done. The only future thing it will need is attaching projectiles to BasePower. I'll make changes to make it more elegant later, but closing it now.
